# docker compose -f docker-compose.agentbox.yml run --rm --build agentbox
services:
  agentbox:
    build:
      context: .
      dockerfile: Dockerfile.agentbox
    environment:
      - VENV_DIR_PATH=/home/alex/.venv
      - UV_PROJECT_ENVIRONMENT=/home/alex/.venv  # required to say UV not to create new venv in wrong place
      - GOPATH=/home/alex/go
    volumes:
      # claude code
      - ~/.claude.json:/home/alex/.claude.json
      - ~/.claude/:/home/alex/.claude/
      # copilot
      - ~/.copilot/:/home/alex/.copilot/
      # project files
      - ./:/home/alex/app
      - ~/.go/:/home/alex/go
      - ~/.cache/uv:/home/alex/.cache/uv

